### ISSUE TITLE
All feedback appears to come from Kari

### ISSUE THREAD

**Issue by droberts-ada** [Ada-Developers-Academy/ada-prs#12]
![image](https://cloud.githubusercontent.com/assets/21064499/22842085/c95eca2a-ef88-11e6-8f1c-1b6ba912f76e.png)

The app should use the instructor's github credentials to post feedback.

**Comment by kariabancroft** [comment]
This has been resolved - @Hamled, can you let us know when you deploy this update? Thanks!

**Comment by Hamled** [comment]
Oh yeah, my bad. This has been deployed.
