### ISSUE TITLE
Need better support for group projects

### ISSUE THREAD

**Issue by droberts-ada** [Ada-Developers-Academy/ada-prs#24]
As it stands, there's no way to see who's in a group together, or to make sure that feedback goes to both group members. Also, half the students look like they haven't submitted.

**Comment by kariabancroft** [comment]
@droberts-ada This functionality is built. The problem with the Word Guess assignment is that both people didn't use git. Once they both use git and the Repo is set up as a group project, it will serach collaborators and associate the single group's PR with both students.
