### ISSUE TITLE
Tables have stopped sorting!

### ISSUE THREAD

**Issue by droberts-ada** [Ada-Developers-Academy/ada-prs#40]
Previously, you could click the little icon in the table headers and it would sort the table, at least on the submission page. That functionality currently does not appear.

Probably a mis-merge. I will go attempt to fix right now.

**Comment by droberts-ada** [comment]
Hahaha this is my bad, I did not test that tables still sort after adding epiceditor.

**Comment by sudocrystal** [comment]
I was just about to come add this comment. That sorting by date submitted does not appear to actually sort by date submitted... it does do something though! :)
